steps:
  - name: gcr.io/$PROJECT_ID/testrunner
    args:
      - '-c'
      - >
        echo Pulling image dev image with tag $SHORT_SHA ... 

        docker pull
        $LOCATION-docker.pkg.dev/$_DEV_PROJECT_ID/$_GAR_DEV_REPO/$_GAR_PACKAGE:$SHORT_SHA

        echo Tagging pulled image as a release candidate $TAG_NAME ...

        docker tag
        $LOCATION-docker.pkg.dev/$_DEV_PROJECT_ID/$_GAR_DEV_REPO/$_GAR_PACKAGE:$SHORT_SHA
        $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_RELEASES_REPO/$_GAR_PACKAGE:$TAG_NAME

        echo Pushing tagged image to release GAR ...

        docker push
        $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_RELEASES_REPO/$_GAR_PACKAGE:$TAG_NAME

        gcloud run deploy sic-classification-vector-store
        --image=$LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_RELEASES_REPO/$_GAR_PACKAGE:$TAG_NAME
        --region $LOCATION --project $_PREPROD_PROJECT_ID

        export
        SIC_VECTOR_STORE_URL="https://sic-classification-vector-store-$_PREPROD_PROJECT_NUMBER.$LOCATION.run.app/v1/sic-vector-store"

        export SA_ID_TOKEN=`gcloud auth print-identity-token
        --impersonate-service-account=$_API_SA`

        echo Waiting 5 minutes to allow API to get ready...

        sleep 300

        pytest cicd
    id: Tag and push release image, deploy to preprod and run smoke tests
    entrypoint: bash
timeout: 1000s
options:
  logging: CLOUD_LOGGING_ONLY
