steps:
  - name: gcr.io/ons-cicd-surveyassist/testrunner
    args:
      - '-c'
      - |
        gcloud --version
        make --version
        pip --version
        python --version
        pytest --version
        poetry --version
    id: Verify Base Tooling Versions
    entrypoint: bash
  - name: gcr.io/ons-cicd-surveyassist/testrunner
    args:
      - '-c'
      - |
        poetry install
        make all-tests
    id: Run Unit Tests
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_GAR_SIC_VECTOR_STORE_IMAGE
      - .
    id: Build SIC Vector Store Docker Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GAR_SIC_VECTOR_STORE_IMAGE
    id: Package SIC Vector Store Docker Image In GAR
  - name: gcr.io/ons-cicd-surveyassist/testrunner
    args:
      - '-c'
      - >
        gcloud run deploy sic-classification-vector-store
        --image=$_GAR_SIC_VECTOR_STORE_IMAGE --region europe-west2 --project
        $_SANDBOX_PROJECT_ID --no-allow-unauthenticated
    id: Deploy SIC Vector Store API
    entrypoint: bash
  - name: gcr.io/ons-cicd-surveyassist/testrunner
    args:
      - '-c'
      - >
        export SIC_VECTOR_STORE_URL=$_SIC_VECTOR_STORE_URL/v1/sic-vector-store export
        SA_ID_TOKEN=`gcloud auth print-identity-token
        --impersonate-service-account=$_API_SA`

        echo Waiting 3 minutes to allow API to get ready...

        sleep 180

        pytest cicd
    id: Run SIC Vectore Store API Smoke Tests
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
